#!/bin/sh
#
# This file is part of Liri.
#
# Copyright (C) 2019 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# $BEGIN_LICENSE:MIT$
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# $END_LICENSE$
#

repodir=$1

if [ -z "$repodir" ]; then
    echo "Usage: $0 [git clone path]"
    exit 1
fi

templatesdir=$(dirname `readlink -f $0`)/templates

if [ ! -d $templatesdir ]; then
    echo "Can't find GitHub templates!"
    exit 1
fi

cp $templatesdir/CODE_OF_CONDUCT.md $repodir/
cp $templatesdir/CONTRIBUTING.md $repodir/.github/
cp $templatesdir/ISSUE_TEMPLATE.md $repodir/.github/
cp $templatesdir/PULL_REQUEST_TEMPLATE.md $repodir/.github/
