#!/bin/bash
#
# Copyright (C) 2016 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

cmake_ver=3.3
ecm_ver=5.12

dir=`pwd`

# cmake
if [ ! -d $dir/.cmake ]; then
    wget --no-check-certificate http://www.cmake.org/files/v${cmake_ver}/cmake-${cmake_ver}.0-Linux-x86_64.tar.gz -O cmake.tar.gz
    tar -xzf cmake.tar.gz -C $dir
    mv $dir/cmake-${cmake_ver}.0-Linux-x86_64 $dir/.cmake
fi
cmake --version

# extra-cmake-modules
if [ ! -d $dir/.ecm ]; then
    wget --no-check-certificate http://download.kde.org/stable/frameworks/${ecm_ver}/extra-cmake-modules-${ecm_ver}.0.tar.xz -O ecm.tar.xz
    tar -xJf ecm.tar.xz
    pushd extra-cmake-modules-${ecm_ver}.0
    rm -rf build
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$dir/.ecm
    make && make install
    popd
fi
